# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "gather"
client_id = "d95ed81401b7bf049f5a1a83a11cc4d0"
application_url = "https://extract-grenada-finger-highly.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://extract-grenada-finger-highly.trycloudflare.com/auth/callback",
  "https://extract-grenada-finger-highly.trycloudflare.com/auth/shopify/callback",
  "https://extract-grenada-finger-highly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "webvisdev.myshopify.com"
